Implemented Sorting and Merging
SambitKSahu99/LogAggregatorTool pull request #1
Opened 2024-06-10 09:15 UTC by SambitKSahu99

Added sorting and merging functionality and wrote the data into an output file.

2024-06-12 07:15 UTC, divya-sathyan commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        Scanner logFolderPathscanner = new Scanner(System.in);
logFolderPathscanner
for scanner make S capital

2024-06-12 07:20 UTC, divya-sathyan commented on src/main/java/org/logAggregatorTool/operation/LogFilesProcessor.java
Remove empty lines

2024-06-12 07:52 UTC, divya-sathyan commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        String userInput1 = logFolderPathscanner.next();
Rename userInput1 to userInputName

2024-06-12 07:53 UTC, divya-sathyan commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
>          } catch (Exception e) {
Instated of using e rename it to  exception

2024-06-12 08:55 UTC, ashutosh-2609 commented on .idea/workspace.xml
Do not commit unwanted files

2024-06-12 08:58 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
>      public static void main(String[] args) throws ExecutionException, InterruptedException {
Multiple functionalities inside main() is not recommended

2024-06-12 08:59 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        Scanner logFolderPathscanner = new Scanner(System.in);
Rename to logFolderPathFromUser

2024-06-12 09:02 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +            if(userInput1.equalsIgnoreCase(Constants.NO_STRING)) System.exit(0);
I suggest give a proper exit message before terminating the program

2024-06-12 09:04 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
>          ExecutorService logExecutorService = Executors.newFixedThreadPool(1);
Find a method which is useful for single thread implementation

2024-06-12 09:07 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
>      public static void main(String[] args) throws ExecutionException, InterruptedException {
Handle the exception and make use of proper error message instead throwing
Make sure it should be understandable for user

2024-06-12 09:07 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +                userInput1 = logFolderPathscanner.next();
logFolderPathscanner not in camel case

2024-06-12 09:12 UTC, ashutosh-2609 commented on build.gradle.kts
> +    implementation(
keep it same as other implementation statements

2024-06-12 09:14 UTC, vinodkadam22 requested changes

2024-06-12 09:14 UTC, vinodkadam22 commented on src/main/java/org/logAggregatorTool/utility/Validations.java
> +
Add this Validation class in validation package

2024-06-12 09:14 UTC, vinodkadam22 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String YES_STRING = "yes";
Move constants class into constants package

2024-06-12 09:14 UTC, vinodkadam22 commented on src/main/java/org/logAggregatorTool/utility/Validations.java
> +    }
What is path ?
rename the path

2024-06-12 09:14 UTC, vinodkadam22 commented on src/main/java/org/logAggregatorTool/writer/LogDataWriter.java
> +        String timeStamp = "";
Move this to constants

2024-06-12 09:14 UTC, vinodkadam22 commented on src/main/java/org/logAggregatorTool/writer/LogDataWriter.java
> +
Remove empty lines

2024-06-12 09:14 UTC, vinodkadam22 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String WELCOME_MESSAGE = "**** Log Aggregator Tool ****";
All the constants must be alphabetic order

2024-06-12 09:14 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        System.out.println(logFuture.get());
Which information your are prompting to user
Please define it properly

2024-06-12 09:18 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
> +            logPreparedStatement.setString(1, logRecord.getLogFileFolderPath());
Try finding more generic terms to populate the logPreparedStatement data.
Now if u do any column change in table u have to change the code as well. Try to encounter these issues

2024-06-12 09:19 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
> +            e.printStackTrace();
Please prompt a proper error message along with StackTrace

2024-06-12 09:19 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +
Remove empty lines

2024-06-12 09:20 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +    String errorMessage;
keep one line gap after line 20

2024-06-12 09:20 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +public class LogRecord {
Please add class level documentation

2024-06-12 09:23 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogFilesProcessor.java
> +    public void logOperation(List<File> logFileList) throws IOException {
Make use of try catch 
or custom exception with proper error message
Straightway throwing exception will make user confuse

2024-06-12 09:25 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +            if (fileList.length == 0) throw new RuntimeException(Constants.FILE_NOT_FOUND_MESSAGE);
make use of fileList.isEmpty()

2024-06-12 09:26 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +            File[] fileList = (new File(logFilesFolderPath)).listFiles();
List can be used

2024-06-12 09:27 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +            logFileList = Arrays.stream(fileList).filter(file -> file.getName().endsWith(Constants.LOG_FILE_EXTENSION)).toList();
Are u able to prompt user which file is invalid ?

2024-06-12 09:31 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +    private final String logFilesFolderPath;
Class level variables are not recommended unless they are getting used in different files
Please make use of local variables and Try passing through function params.

2024-06-12 09:31 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +    public String call() throws Exception {
Bunch of business logic inside call() is not allowed

2024-06-12 09:34 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +public class LogThread implements Callable<String> {
This class is responsible for multiple functionalities
Try renaming it to more specific

2024-06-12 09:36 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +     * @return Returns Log Record Object
Please define what data LogRecord object holds in documentation

2024-06-12 09:36 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/reader/LogDataReader.java
> +public class LogDataReader {
REname to Log file Reader

2024-06-12 09:37 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/reader/LogDataReader.java
> +        for (File logFile : logFilesList) {
What the use of a different sorted time stamp list when you can make use of Map keys
Try finding a way out there

2024-06-12 09:39 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/reader/LogDataReader.java
> +                boolean check = false;
Please rename the variable to more specific terms, for which it is used for

2024-06-12 09:39 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String WELCOME_MESSAGE = "**** Log Aggregator Tool ****";
Keep the constant file in Alphabetic order

2024-06-12 09:40 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +public class Constants {
Rename the File more specific to project

2024-06-12 09:41 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/utility/JdbcConstants.java
> +public class JdbcConstants {
Rename to DatabaseConstants

2024-06-12 09:42 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/utility/Validations.java
> +    public static boolean validateFolderPath(String path) {
rename to isValidFolderPath()
methods returning boolen should be renamed as above

2024-06-12 13:26 UTC, divya-sathyan requested changes

2024-06-13 06:11 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        Scanner logFolderPathscanner = new Scanner(System.in);
Resolved

2024-06-13 06:11 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogFilesProcessor.java
Resolved

2024-06-13 06:11 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        String userInput1 = logFolderPathscanner.next();
Resolved

2024-06-13 06:12 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
>          } catch (Exception e) {
Resolved

2024-06-13 06:12 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +            if(userInput1.equalsIgnoreCase(Constants.NO_STRING)) System.exit(0);
Resolved

2024-06-13 06:12 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +                userInput1 = logFolderPathscanner.next();
Resolved

2024-06-13 06:13 UTC, SambitKSahu99 commented on build.gradle.kts
> +    implementation(
Resolved

2024-06-13 06:13 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
> +        String logFileNames = "";
Resolved

2024-06-13 06:13 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +}
Resolved

2024-06-13 06:13 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +    private String outputFileName;
Resolved

2024-06-13 06:13 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String YES_STRING = "yes";
Resolved

2024-06-13 06:14 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Validations.java
> +    }
Resolved

2024-06-13 06:14 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/writer/LogDataWriter.java
> +        String timeStamp = "";
Resolved

2024-06-13 06:14 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String WELCOME_MESSAGE = "**** Log Aggregator Tool ****";
Resolved

2024-06-13 06:14 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        System.out.println(logFuture.get());
Resolved

2024-06-13 06:14 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +
Resolved

2024-06-13 06:14 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +    String errorMessage;
Resolved

2024-06-13 06:15 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dto/LogRecord.java
> +public class LogRecord {
Resolved

2024-06-13 06:15 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogFilesProcessor.java
> +        List<String> timeStampList = new ArrayList<>();
Resolved

2024-06-13 06:15 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogFilesProcessor.java
> +    public void logOperation(List<File> logFileList) throws IOException {
Throw exception is being handled by calling method using try catch

2024-06-13 06:17 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +            if (fileList.length == 0) throw new RuntimeException(Constants.FILE_NOT_FOUND_MESSAGE);
Resolved

2024-06-13 06:17 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +            File[] fileList = (new File(logFilesFolderPath)).listFiles();
Resolved

2024-06-13 06:18 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +    private final String logFilesFolderPath;
Resolved

2024-06-13 06:18 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogThread.java
> +public class LogThread implements Callable<String> {
Resolved

2024-06-13 06:18 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/reader/LogDataReader.java
> +public class LogDataReader {
Resolved

2024-06-13 06:19 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String WELCOME_MESSAGE = "**** Log Aggregator Tool ****";
Resolved

2024-06-13 06:19 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +public class Constants {
Resolved

2024-06-13 06:19 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/JdbcConstants.java
> +public class JdbcConstants {
Resolved

2024-06-13 06:19 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Validations.java
> +    public static boolean validateFolderPath(String path) {
Resolved

2024-06-13 06:19 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String YES_STRING = "yes";
Resolved

2024-06-13 06:20 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
> +    public static final String NO_STRING = "no";
Resolved

2024-06-13 06:21 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/Constants.java
>      public static final String DATE_PATTERN = "^[0-9]{4}/(0[1-9]|1[0-2])/(0[1-9]|[1-2][0-9]|3[01]).*";
Resolved

2024-06-13 06:23 UTC, SambitKSahu99 commented on .idea/workspace.xml
Resolved

2024-06-13 06:25 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        while(!Validations.validateFolderPath(userInput1)){
Need more clarification

2024-06-13 11:42 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +    private static String logFilesFolderPathUserInputProcessor(){
Rename to userInputProcessor()

2024-06-13 11:43 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        while(!LogAggregatorToolValidations.isValidFolderPath(logFilesFolderPathUserInput)){
Please use one spaces before starting ()
while ()
if () ...

2024-06-13 11:45 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/constants/LogAggregatorToolConstants.java
> +    public static final int DEFAULT_INT_VALUE =  0;
public static final int DEFAULT_INT_VALUE =  0; remove one space
 
  public static final int DEFAULT_INT_VALUE = 0;

2024-06-13 11:47 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
> +            logPreparedStatement.close();
Is the connection will be closed in case exception happens ?
Make sure to close all the db connections

2024-06-13 11:50 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/reader/LogFileReader.java
> +                boolean check = false;
keep variable name more specific to its usage

2024-06-13 11:51 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/reader/LogFileReader.java
> +                        logTimeStampKey = logDataLine.substring(LogAggregatorToolConstants.DEFAULT_INT_VALUE, LogAggregatorToolConstants.SUBSTRING_END_INDEX);
these linse are out side if block so remove the tab spacing

2024-06-13 11:53 UTC, ashutosh-2609 commented on src/main/java/org/logAggregatorTool/writer/LogDataWriter.java
> +                    String logData;
Why it is declared inside loop

2024-06-13 12:07 UTC, divya-sathyan commented on .gitignore
Don't commit unwanted file

2024-06-13 12:28 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +    private static String logFilesFolderPathUserInputProcessor(){
Resolved

2024-06-13 12:28 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/LogAggregatorTool.java
> +        while(!LogAggregatorToolValidations.isValidFolderPath(logFilesFolderPathUserInput)){
resolved

2024-06-13 12:30 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/constants/LogAggregatorToolConstants.java
> +    public static final int DEFAULT_INT_VALUE =  0;
resolved

2024-06-13 12:31 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/dao/AuditEntry.java
> +            logPreparedStatement.close();
Yes it will get closed automatically if any exception occurs

2024-06-13 12:33 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/reader/LogFileReader.java
> +                boolean check = false;
resolved

2024-06-13 12:33 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/reader/LogFileReader.java
> +                        logTimeStampKey = logDataLine.substring(LogAggregatorToolConstants.DEFAULT_INT_VALUE, LogAggregatorToolConstants.SUBSTRING_END_INDEX);
resolved

2024-06-13 12:33 UTC, SambitKSahu99 commented on .gitignore
resolved

2024-06-13 12:34 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/writer/LogDataWriter.java
> +                    String logData;
resolved

2024-06-13 12:38 UTC, divya-sathyan commented on src/main/java/org/logAggregatorTool/operation/LogFilesFolderProcessor.java
> +        for (File file : filesList) {
rename file

2024-06-14 05:54 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/operation/LogFilesFolderProcessor.java
> +        for (File file : filesList) {
resolved

2024-06-14 05:54 UTC, SambitKSahu99 commented on src/main/java/org/logAggregatorTool/utility/LogAggregatorToolValidations.java
> +    public static boolean isValidLogFile(File file) {
resolved

2024-06-14 06:32 UTC, vinodkadam22 approved these changes

2024-06-14 08:50 UTC, ashutosh-2609 approved these changes

2024-06-14 09:12 UTC, merged